### ISSUE TITLE
CO2 brine example not working

### ISSUE THREAD

**Issue by pw0908** [sintefmath/JutulDarcy.jl#22]
Hi!

I just tried running the `co2_brine_2d_vertical.jl` on my machine (all packages fully up to date) and it fails on the 57th time step:
```julia
julia> include("co2_brine_2d_vertical.jl")
Simulation aborted Completed 57 of 206 timesteps in 13 seconds, 844 milliseconds and 754 iterations.
╭────────────────┬──────────┬───────────────┬──────────────┬─────────────╮
│ Iteration type │ Avg/step │  Avg/ministep │     Time per │       Total │
│                │ 58 steps │ 138 ministeps │ Milliseconds │    (wasted) │
├────────────────┼──────────┼───────────────┼──────────────┼─────────────┤
│ Newton         │     13.0 │       5.46377 │      18.3607 │   754 (525) │
│ Linearization  │  15.3793 │       6.46377 │      15.5201 │   892 (560) │
│ Linear solver  │   85.931 │       36.1159 │       2.7777 │ 4984 (3663) │
╰────────────────┴──────────┴───────────────┴──────────────┴─────────────╯
╭────────────────┬──────────────┬────────────┬─────────╮
│ Timing type    │         Each │   Relative │   Total │
│                │ Milliseconds │ Percentage │ Seconds │
├────────────────┼──────────────┼────────────┼─────────┤
│ Properties     │       2.5779 │    14.04 % │  1.9437 │
│ Equations      │       3.1939 │    20.58 % │  2.8490 │
│ Assembly       │       1.2797 │     8.25 % │  1.1415 │
│ Linear solve   │       2.0008 │    10.90 % │  1.5086 │
│ Preconditioner │       1.1168 │     6.08 % │  0.8420 │
│ Update         │       0.9086 │     4.95 % │  0.6851 │
│ Convergence    │       1.9364 │    12.48 % │  1.7273 │
│ Input/Output   │       0.0806 │     0.08 % │  0.0111 │
│ Other          │       4.1586 │    22.65 % │  3.1356 │
├────────────────┼──────────────┼────────────┼─────────┤
│ Total          │      18.3607 │   100.00 % │ 13.8440 │
╰────────────────┴──────────────┴────────────┴─────────╯
┌ Error: Simulation did not complete successfully.
└ @ Jutul ~/.julia/packages/Jutul/hWGJY/src/simulator/print.jl:144
```
Not quite sure where to look but I thought I would point it out.

**Comment by moyner** [comment]
Thanks for spotting this! I have pushed out a new release for MultiComponentFlash that fixes the single phase labelling code and this example. It should fix the issue once the release is out: https://github.com/JuliaRegistries/General/pull/94034

**Comment by pw0908** [comment]
Thanks! We're just trying to get Clapeyron.jl to work with JutulDarcy.jl. We now have the MultiComponentFlash.jl extension working in our next release!

It appears that most extension we'd need to account for would be relating to the `MultiPhaseCompositionalSystemLV` objects. Is there anything else that we should also consider when writing this extension?

**Comment by moyner** [comment]
It would be very nice if we can run multiphase flow with equations of state from Clapeyron.jl. I think that if the flash extension works, then the most important part is that there is some logic in flow_coupler.jl (in MultiComponentFlash) and src/multicomponent (JutulDarcy) that needs to work. This is related to caching for efficient updates and AD tricks to get the derivatives of the flash outputs needed for flow (e.g. phase saturations) with respect to the primary variables used in the flow solver. This part of the code is a bit complex and not so clean in terms of dispatches, but conceptually I think it could work.
