### ISSUE TITLE
Error in well output for JutulSPE1.m

### ISSUE THREAD

**Issue by nikolai-andrianov** [sintefmath/JutulDarcy.jl#39]
Hello,

There is an error in writing wells data when simulating JutulSPE1.m.

MRST model: Writing output to C:\Matlab\mrst-2023b\output\jutul\ODEHPROBLEM-IMPLICITOPTION-1200DAYS_GenericBlackOilModel_output_mrst.
ERROR: MethodError: no method matching full_well_outputs(::Jutul.MultiModel{nothing}, ::Vector{Dict{Symbol, Any}}, ::Dict{Any, Any}; shortname::Bool)

Best regards,
Nikolai

**Comment by moyner** [comment]
Hi! Thanks for reporting this. We are planning a new MRST release this week and will fix this before then. In the mean time, it is possible to simulate directly from the input file in JutulDarcy if you want to test.

**Comment by moyner** [comment]
I think this should be fixed with the latest release. Can you update your environment (`using Pkg; Pkg.update()`), restart Julia and try again?
