### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by joylin1984** [sintefmath/JutulDarcy.jl#41]
Is there a plan to add the following features:

1.  Analysis Aquifer,   such as Fetkovich aquifer, Carter-Tracy aquifer 
2.  Output ECL binary format file,  such as egrid, unrst, etc.   Convenient to view calculation results in ResInsight.

**Comment by moyner** [comment]
Hi, thanks for your interest! I think that it is likely that some aquifer variants will be added to the solvers sometime in the future, but I do not have a schedule for this - this code is research driven, so I will most likely add it when I'm working on a model where this is an important feature.

There are currently no plans to write ECL output. There is a built in visualiser you can use for 3D plotting and well curves, but it is  much simpler than ResInsight. There's some examples with screenshots in the documentation: https://sintefmath.github.io/JutulDarcy.jl/dev/examples/data_input_file/#Plot-the-simulation-model
https://sintefmath.github.io/JutulDarcy.jl/dev/examples/data_input_file/#Plot-the-well-responses

**Comment by joylin1984** [comment]
Thanks for your reply. Hope this project can develop well in the long term.
I will close this issue.
Regards.

**Comment by moyner** [comment]
Hi, analytical aquifers are still missing, but numerical and constant pressure/head aquifers have been added in the leatest release.
