### ISSUE TITLE
bottom hole pressure

### ISSUE THREAD

**Issue by zhen0z** [sintefmath/JutulDarcy.jl#63]
Hi Olav,

I do have another question about bottom hole pressure. I noticed that the pressure currently only reflects values at or near the top perforation layer.

Would it be possible to include the pressure data for all perforation layers in the well?

Thanks!
Zhen

**Comment by moyner** [comment]
Hi, this is computed internally in the code. For a simple well (`simple_well = true` during well setup) you can get it this way:
```julia
push!(model[:WellName].output_variables, :ConnectionPressureDrop)
```
You can then use this pressure drop to get the values in each perforation by adding it to the BHP.

The alternative is to use `simple_well=false`. In that case you will get out the pressures of the well nodes in each perforation directly in the state.

**Comment by zhen0z** [comment]
Sorry for the late reply, I've been trying it recently, and it works fine now, thanks!

**Comment by moyner** [comment]
Happy to hear that! Closing this issue, feel free to reopen if you have follow-ups.
