### ISSUE TITLE
setting custom objective function

### ISSUE THREAD

**Issue by miguelcorralesg** [sintefmath/JutulDarcy.jl#69]
Hi Olav,

I’m setting up a custom objective function and wanted to update this thread with some findings and issues I’ve encountered, as it might be helpful for others with similar questions in the future.

I’m trying to use the L2 norm between observed and simulated well data as the objective. To achieve this, I’m using the `compute_well_qoi` function, and the current code is as follows:

```julia
function objective_function(model, state, Δt, step_i, forces)
    grat_ = JutulDarcy.compute_well_qoi(model, state, forces, :Producer, SurfaceGasRateTarget)
    # Compute squared difference
    square_difference_grat = (grat_ - qg_true[step_i])^2

    return Δt * square_difference_grat
end

data_domain_with_gradients = JutulDarcy.reservoir_sensitivities(case, result, objective_function, include_parameters = true)
```

One thing I noticed is that if the rate comes from a producer well (when using `compute_well_qoi`), it follows the sign convention, meaning it will be negative (so the sign of the observed data needs attention --> watch out with the signs). Based on your paper https://www.earthdoc.org/content/papers/10.3997/2214-4609.202437111 and other references, I understand if I want to compute the gradient for multiple wells, I should use a loop to accumulate the `grat_` variable for each well.

-----

**Comment by moyner** [comment]
Hi! Sorry for the late reply. I think it sounds like you resolved the issue by looking at the code. Your explanation sounds correct to me. The latest release actually contains a history matching example that should be helpful for your work:

https://github.com/sintefmath/JutulDarcy.jl/blob/main/examples/cgnet_egg.jl

The docs are building right now, but the preview can be seen here: https://sintefmath.github.io/JutulDarcy.jl/previews/PR71/examples/cgnet_egg

**Comment by miguelcorralesg** [comment]
Hi Olav, 

Thanks a lot for your answer, the examples you provided are really helpful. Much appreciated.
